[workspace]
members = ["invoke", "programs/*"]
resolver = "2"

[workspace.dependencies]
solana-program = "1.18"
solana-nostd-entrypoint = { git = "https://github.com/Aursen/solana-nostd-entrypoint" }
