[package]
name = "nostd-system-program"
version = "0.1.0"
edition = "2021"

[dependencies]
solana-program.workspace = true
solana-nostd-entrypoint.workspace = true
nostd-entrypoint-invoke = { path = "../invoke" }
